language: rust
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo test --verbose --all --features stats
rust:
  - 1.20.0
  - 1.21.0
  - 1.22.0
  - 1.23.0
  - 1.24.0
  - 1.25.0
  - stable
